[project]
name = "simpletexc"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "banian", email = "1633757055@qq.com" }
]
dependencies = [
    "flet>=0.85.2"
]

[dependency-groups]
dev = [
    "flet-cli>=0.85.2",
    "flet-desktop>=0.85.2",
    "flet-web>=0.85.2",
    "pyinstaller>=6.0",
]

[tool.flet.pack]
add-data = "src/assets:assets"
product-name = "simpletexC"
company-name = "simpletexC"
copyright = "Copyright (C) 2023-2026 by simpletexC"
bundle = "dir"
console = false

[tool.flet]
org = "com.mycompany"
product = "simpletexc"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"

[tool.flet.app]
path = "src"
